---
  - name: Launch "{{ visibility }}" Linux instance
    os_server:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      name: linux-{{ visibility }}-{{ sid }}
      state: present
      key_name: "{{ key_name }}"
      availability_zone: "{{ az }}"
      nics:
        - net-name: student-{{ sid }}-{{ visibility }}net
      image: "{{ image_uid }}"
      flavor: "{{ flavor_name }}"
      security_groups: "{{ security_group }}"
      auto_ip: no
      user_data: |
        #cloud-config
        ssh_pwauth: True
        disable_root: false
        chpasswd:
          list: |
            root:redhat
          expire: false
