---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  tasks:

  - stat: path="{{ config_file }}"
    register: st
  - include_vars: "{{ config_file }}"
    when: st.stat.exists and st.stat.isreg

  - name: Authenticate to OpenStack environment defined in credentials
    os_auth: 
      cloud: devstack

  - name: Get facts for instance
    os_server_facts:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      server: "{{ vm_name }}"
    register: vm

  - debug:
      var: vm.ansible_facts.openstack_servers[0].image.id
    
  - name: Rebuild Instance
    os_server_actions:
      cloud: devstack
      auth: 
        project_name: student-{{ sid }}
      server: "{{ vm_name }}"
      action: rebuild
      image: "{{ vm.ansible_facts.openstack_servers[0].image.id }}"
