---
- hosts: localhost
  connection: local
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  tasks:

  - stat: path="{{ config_file }}"
    register: st
  - include_vars: "{{ config_file }}"
    when: st.stat.exists and st.stat.isreg

  - name: Authenticate to OpenStack environment defined in credentials
    os_auth: 
      cloud: devstack

  - name: Remove "{{ sid }}" router
    os_router:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      state: absent
      name: router-student-{{ sid }}
      network: public
      project: student-{{ sid }}

  - name: Remove the central-range port
    os_port:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      state: absent
      name: port-{{ sid }}
      network: central-range

  - name: Terminate instances
    os_server:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      name: '{{ item }}'
      state: absent
    with_items:
      - linux-hidden-{{ sid }}
      - win-hidden-{{ sid }}
      - linux-visible-{{ sid }}
      - win-visible-{{ sid }}

  - name: Remove visible subnet
    os_subnet:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      name: student-{{ sid }}-visiblesub
      network_name: student-{{ sid }}-visiblenet 
      state: absent

  - name: Remove hidden subnet
    os_subnet:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      name: student-{{ sid }}-hiddensub
      network_name: student-{{ sid }}-hiddennet
      state: absent

  - name: Remove student-{{sid }} hidden network
    os_network:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      name: student-{{ sid }}-hiddennet
      state: absent

  - name: Remove student-{{ sid }} visible network
    os_network:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      name: student-{{ sid }}-visiblenet
      state: absent

  - name: Remove Student Project
    os_project:
      name: student-{{ sid }}
      state: absent
      cloud: devstack
      endpoint_type: admin

