--- 
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: add a thing
    os_router:
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: student-{{ sid }}
      state: present
      name: router-student-{{ sid }}
      network: public
      project: student-{{ sid }}
      interfaces:
        - student-{{ sid }}-visiblesub
        - student-{{ sid }}-hiddensub
        - net: central-range
          subnet: central-range-sub
          portip: 172.16.250.1{{ sid }}
