---
- hosts: all
  gather_facts: no
  tasks: 
  - name: Add central-range port to student "{{ sid }}" router
    shell: source /home/stack/overcloudrc; openstack router add port router-student-{{ sid }} port-{{ sid }}
    when: inventory_hostname != "localhost"
