--- 
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: create port
    os_port:
      auth:
        project_name: student-{{ sid }}
      state: present
      name: port-{{ sid }}
      network: central-range
      fixed_ips:
        - ip_address: 172.16.250.1{{ sid }}
  - name: add a thing
    os_router:
      auth:
        project_name: student-{{ sid }}
      state: present
      name: router-student-{{ sid }}
      network: public
      project: student-{{ sid }}
      interfaces:
        - student-{{ sid }}-visiblesub
        - student-{{ sid }}-hiddensub
        - net: central-range
          subnet: central-range-sub
          portip: 172.16.250.1{{ sid }}
