---
- hosts: localhost
  connection: local
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  tasks: 
  - stat: path="{{ config_file }}"
    register: st
  - include_vars: "{{ config_file }}"
    when: st.stat.exists and st.stat.isreg
  - name: Authenticate to OpenStack environment defined in credentials
    os_auth:
      cloud: devstack
  - include_role:
      name: cf_service


