---
# tasks file for roles/project
  - name: Create Student Project
    os_project:
      name: student-{{ sid }}
      state: present
      cloud: devstack
      endpoint_type: admin

  - name: Add operator to student project
    os_user_role:
      user: operator
      role: "{{ item }}"
      cloud: devstack
      project: student-{{ sid }}
      endpoint_type: admin
    with_items:
      - admin
      - Member
