---
# tasks file for roles/project
  - name: Create Student Project
    os_project:
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"
      name: student-{{ sid }}
      state: present
      endpoint_type: admin
