---

  - name: Launch "{{ visibility }}" Windows instance
    os_server:
      cloud: devstack
      auth:
        project_name: student-{{ sid }}
      name: win-{{ visibility }}-{{ sid }}
      state: present
      key_name: "{{ key_name }}"
      availability_zone: "{{ az }}"
      nics:
        - net-name: student-{{ sid }}-{{ visibility }}net
      image: "{{ win_image }}"
      flavor: "{{ win_flavor }}"
      security_groups: "{{ security_group }}"
      auto_ip: no
